### ISSUE TITLE
Langchain example: don't need explicit openai api key checks

### ISSUE THREAD

**Issue by dev2049** [kinsta/hello-world-langchain#1]
for what it's worth don't think you should need this [here](https://github.com/kinsta/hello-world-langchain/blob/a18ef916b5af22e4c1f5041b3c1627a328bbc998/main.py#L12)
```python
if not os.environ.get('OPENAI_API_KEY'):
    raise Exception("OPENAI_API_KEY is not set")

openai.api_key = os.getenv("OPENAI_API_KEY")
```

all of this is checked / set when langchain llm object is instantiated. as long as you've set the api key env var you're good to go :)

**Comment by kristofdombi** [comment]
@dev2049 Thank you very much! 🙇‍♂️ I'll open a PR about this.
